CREATE TABLE `pricing_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`category` varchar(64) NOT NULL,
	`brand` varchar(128) NOT NULL,
	`size` varchar(32) NOT NULL,
	`condition` varchar(32) NOT NULL,
	`defectLevel` varchar(32),
	`color` varchar(64),
	`style` varchar(64),
	`originalPrice` int,
	`recommendedPrice` int NOT NULL,
	`fastSalePrice` int NOT NULL,
	`highValuePrice` int NOT NULL,
	`marketMin` int NOT NULL,
	`marketMax` int NOT NULL,
	`sellabilityScore` int NOT NULL,
	`confidenceScore` int NOT NULL,
	`intlPriceUSD` int,
	`consensusLevel` varchar(32),
	`agentCount` int,
	`imageUrl` text,
	`listingData` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `pricing_history_id` PRIMARY KEY(`id`)
);
