CREATE TABLE `wardrobe` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`category` varchar(64) NOT NULL,
	`brand` varchar(128) NOT NULL,
	`color` varchar(64),
	`material` varchar(64),
	`condition` varchar(32) NOT NULL,
	`conditionScore` int,
	`defects` text,
	`size` varchar(32),
	`height` int,
	`weight` int,
	`bust` int,
	`shoulder` int,
	`waist` int,
	`hip` int,
	`recommendedPrice` int,
	`marketMin` int,
	`marketMax` int,
	`sellabilityScore` int,
	`confidenceScore` int,
	`imageUrl` text,
	`imageUrl2` text,
	`imageUrl3` text,
	`status` enum('in_wardrobe','listed','sold') NOT NULL DEFAULT 'in_wardrobe',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wardrobe_id` PRIMARY KEY(`id`)
);
