/**
 * SharePanel – แชร์ผลประเมินราคาไปยัง social media
 * มีปุ่มแชร์ Facebook, LINE, Twitter/X, Copy
 * AI-generated caption สร้างอัตโนมัติทันทีที่เปิด (3 ความยาว: สั้น/กลาง/ยาว)
 */
import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { motion, AnimatePresence } from "framer-motion";
import { Share2, Copy, Check, Sparkles, Loader2, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import type { PricingResult } from "@/lib/pricing-engine";

interface Props {
  result: PricingResult;
  category: string;
  brand: string;
  size: string;
  condition: string;
  color?: string;
  style?: string;
  originalPrice?: number;
  selectedPrice?: number;
  visible: boolean;
  onClose: () => void;
}

export default function SharePanel({
  result,
  category,
  brand,
  size,
  condition,
  color,
  style,
  originalPrice,
  selectedPrice,
  visible,
  onClose,
}: Props) {
  const displayPrice = selectedPrice ?? result.recommendedPrice;
  const [caption, setCaption] = useState("");
  const [captionTab, setCaptionTab] = useState("medium");
  const [copied, setCopied] = useState(false);
  const hasAutoGenerated = useRef(false);

  const generateCaption = trpc.ai.generateCaption.useMutation({
    onSuccess: (data) => {
      const captions = data.captions;
      if (captionTab === "short") setCaption(captions.shortCaption);
      else if (captionTab === "long")
        setCaption(captions.longCaption + "\n\n" + captions.hashtags.join(" "));
      else setCaption(captions.mediumCaption + "\n\n" + captions.hashtags.join(" "));
    },
    onError: () => {
      // Silently fall back to default caption
    },
  });

  // Auto-generate caption when panel becomes visible
  useEffect(() => {
    if (visible && !hasAutoGenerated.current && !generateCaption.isPending) {
      hasAutoGenerated.current = true;
      generateCaption.mutate({
        category,
        brand,
        size,
        condition,
        color,
        style,
        recommendedPrice: displayPrice,
        originalPrice,
      });
    }
  }, [visible]);

  // Reset auto-generate flag when panel closes
  useEffect(() => {
    if (!visible) {
      hasAutoGenerated.current = false;
      setCaption("");
    }
  }, [visible]);

  const handleRegenerate = () => {
    generateCaption.mutate({
      category,
      brand,
      size,
      condition,
      color,
      style,
      recommendedPrice: displayPrice,
      originalPrice,
    });
  };

  const handleTabChange = (v: string) => {
    setCaptionTab(v);
    if (generateCaption.data?.captions) {
      const c = generateCaption.data.captions;
      if (v === "short") setCaption(c.shortCaption);
      else if (v === "long") setCaption(c.longCaption + "\n\n" + c.hashtags.join(" "));
      else setCaption(c.mediumCaption + "\n\n" + c.hashtags.join(" "));
    }
  };

  const handleCopy = async () => {
    const text = caption || getDefaultCaption();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("คัดลอกข้อความแล้ว");
    setTimeout(() => setCopied(false), 2000);
  };

  const getDefaultCaption = () => {
    return `ขายเสื้อผ้ามือสอง ${brand} ไซซ์ ${size}\nราคา ฿${displayPrice.toLocaleString()}\nสภาพดี พร้อมส่ง!`;
  };

  const shareText = encodeURIComponent(caption || getDefaultCaption());

  const shareLinks = [
    {
      name: "Facebook",
      color: "bg-[#1877F2] hover:bg-[#166FE5]",
      url: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}&quote=${shareText}`,
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
        </svg>
      ),
    },
    {
      name: "LINE",
      color: "bg-[#00B900] hover:bg-[#00A300]",
      url: `https://line.me/R/share?text=${shareText}`,
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M19.365 9.863c.349 0 .63.285.63.631 0 .345-.281.63-.63.63H17.61v1.125h1.755c.349 0 .63.283.63.63 0 .344-.281.629-.63.629h-2.386c-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.627-.63h2.386c.349 0 .63.285.63.63 0 .349-.281.63-.63.63H17.61v1.125h1.755zm-3.855 3.016c0 .27-.174.51-.432.596-.064.021-.133.031-.199.031-.211 0-.391-.09-.51-.25l-2.443-3.317v2.94c0 .344-.279.629-.631.629-.346 0-.626-.285-.626-.629V8.108c0-.27.173-.51.43-.595.06-.023.136-.033.194-.033.195 0 .375.104.495.254l2.462 3.33V8.108c0-.345.282-.63.63-.63.345 0 .63.285.63.63v4.771zm-5.741 0c0 .344-.282.629-.631.629-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.627-.63.349 0 .631.285.631.63v4.771zm-2.466.629H4.917c-.345 0-.63-.285-.63-.629V8.108c0-.345.285-.63.63-.63.348 0 .63.285.63.63v4.141h1.756c.348 0 .629.283.629.63 0 .344-.282.629-.629.629M24 10.314C24 4.943 18.615.572 12 .572S0 4.943 0 10.314c0 4.811 4.27 8.842 10.035 9.608.391.082.923.258 1.058.59.12.301.079.766.038 1.08l-.164 1.02c-.045.301-.24 1.186 1.049.645 1.291-.539 6.916-4.078 9.436-6.975C23.176 14.393 24 12.458 24 10.314" />
        </svg>
      ),
    },
    {
      name: "X",
      color: "bg-[#000000] hover:bg-[#333333]",
      url: `https://twitter.com/intent/tweet?text=${shareText}`,
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
        </svg>
      ),
    },
  ];

  if (!visible) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 20 }}
        className="bg-card rounded-2xl p-5 border border-border shadow-sm space-y-4"
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Share2 className="w-4 h-4 text-teal-600" />
            <h3 className="text-sm font-semibold text-foreground">แชร์โพสขาย</h3>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose} className="text-xs h-7">
            ปิด
          </Button>
        </div>

        {/* AI Caption Generator */}
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Sparkles className="w-3.5 h-3.5 text-amber-500" />
            <span className="text-xs font-medium text-muted-foreground">
              ข้อความโพสขาย (AI สร้างให้)
            </span>
            {generateCaption.isPending && (
              <Loader2 className="w-3 h-3 animate-spin text-teal-600" />
            )}
          </div>

          {/* Caption length tabs */}
          <Tabs value={captionTab} onValueChange={handleTabChange}>
            <TabsList className="h-7 mb-2">
              <TabsTrigger value="short" className="text-[10px] px-2 h-5">
                สั้น (X)
              </TabsTrigger>
              <TabsTrigger value="medium" className="text-[10px] px-2 h-5">
                กลาง (LINE)
              </TabsTrigger>
              <TabsTrigger value="long" className="text-[10px] px-2 h-5">
                ยาว (FB)
              </TabsTrigger>
            </TabsList>
          </Tabs>

          <div className="relative">
            <Textarea
              value={caption || (generateCaption.isPending ? "" : getDefaultCaption())}
              onChange={(e) => setCaption(e.target.value)}
              className="bg-warm-50 border-warm-200 text-sm min-h-[100px] resize-none"
              placeholder={generateCaption.isPending ? "AI กำลังสร้างข้อความ..." : "ข้อความสำหรับโพสขาย..."}
            />
            {generateCaption.isPending && (
              <div className="absolute inset-0 flex items-center justify-center bg-warm-50/80 rounded-md">
                <div className="flex items-center gap-2 text-teal-600">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span className="text-xs font-medium">AI กำลังสร้างข้อความ...</span>
                </div>
              </div>
            )}
          </div>

          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleRegenerate}
              disabled={generateCaption.isPending}
              className="gap-1.5 text-xs h-8"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              สร้างใหม่
            </Button>
            <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5 text-xs h-8">
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-teal-600" />
                  คัดลอกแล้ว
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  คัดลอก
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Share Buttons */}
        <div className="space-y-2">
          <span className="text-xs font-medium text-muted-foreground">แชร์ไปยัง</span>
          <div className="grid grid-cols-3 gap-2">
            {shareLinks.map((link) => (
              <a
                key={link.name}
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                className={`flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-xl text-white text-xs font-medium transition-all duration-200 ${link.color}`}
              >
                {link.icon}
                {link.name}
              </a>
            ))}
          </div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
